# Generated by Django 3.1.5 on 2021-01-28 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSubmission',
            fields=[
                ('submitter_email', models.EmailField(max_length=254)),
                ('submitter_address', models.TextField()),
                ('the_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitter_json', models.JSONField()),
            ],
        ),
    ]
